### ISSUE TITLE
Support for atomics

### ISSUE THREAD

**Issue by vchuravy** [JuliaGPU/CUDAnative.jl#117]
It seems that device atomics primarily work with the LLVM atomics, except for a few special functions.

### NVVM atomic add, increment, and decrement (for addressspaces: none, 1, 3)
```
declare float @llvm.nvvm.atomic.load.add.f32.p0f32(float* address, float val)
declare i32 @llvm.nvvm.atomic.load.inc.32.p0i32(i32* address, i32 val)
declare i32 @llvm.nvvm.atomic.load.dec.32.p0i32(i32* address, i32 val)
```

### Atomics with scope (only supported on sm_60+)  target feature satom
See https://reviews.llvm.org/D24944 

## TODO
- [ ] Decide if we want a specific `CuAtomic/AtomicPtr` type or can we just work with normal `DevicePtr`
- [ ] Port https://github.com/JuliaLang/julia/blob/master/base/atomics.jl
- [ ] Add support for  nvvm atomic add, increment and decrement
- [ ] Add support for `satomic` on `sm_60` && chekc which LLVM version has support for that.

**Comment by xiaodaigh** [comment]
There is a package for Atomics. I can see atomicadd being implemented

https://github.com/alandion/CUDAatomics.jl

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/CUDAnative.jl/pull/370
